# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import caster_setup_pb2 as caster__setup__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in caster_setup_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.stream_unary(
                '/rtcm.Caster/Publish',
                request_serializer=caster__setup__pb2.PublishMsg.SerializeToString,
                response_deserializer=caster__setup__pb2.PublishAck.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/rtcm.Caster/Subscribe',
                request_serializer=caster__setup__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=caster__setup__pb2.RtcmFrame.FromString,
                _registered_method=True)


class CasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Publish(self, request_iterator, context):
        """base → server (client-stream)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """server → rover (server-stream)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.stream_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=caster__setup__pb2.PublishMsg.FromString,
                    response_serializer=caster__setup__pb2.PublishAck.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=caster__setup__pb2.SubscribeRequest.FromString,
                    response_serializer=caster__setup__pb2.RtcmFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rtcm.Caster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rtcm.Caster', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Caster(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Publish(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/rtcm.Caster/Publish',
            caster__setup__pb2.PublishMsg.SerializeToString,
            caster__setup__pb2.PublishAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rtcm.Caster/Subscribe',
            caster__setup__pb2.SubscribeRequest.SerializeToString,
            caster__setup__pb2.RtcmFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Pipe = channel.stream_stream(
                '/rtcm.Control/Pipe',
                request_serializer=caster__setup__pb2.ControlMsg.SerializeToString,
                response_deserializer=caster__setup__pb2.ControlMsg.FromString,
                _registered_method=True)


class ControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Pipe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Pipe': grpc.stream_stream_rpc_method_handler(
                    servicer.Pipe,
                    request_deserializer=caster__setup__pb2.ControlMsg.FromString,
                    response_serializer=caster__setup__pb2.ControlMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rtcm.Control', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rtcm.Control', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Control(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Pipe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/rtcm.Control/Pipe',
            caster__setup__pb2.ControlMsg.SerializeToString,
            caster__setup__pb2.ControlMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
